apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  db-name: "{{ .Values.database.name }}"
  db-user: "{{ .Values.database.user }}"
  db-host: "{{ .Values.database.host }}"
  db-port: "{{ .Values.database.port }}"
