apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: {{ .Values.namespace }}
data:
  DB_NAME: "{{ .Values.database.name }}"
  DB_USER: "{{ .Values.database.user }}"
  DB_HOST: "{{ .Values.database.host }}"
  DB_PORT: "{{ .Values.database.port }}"
 