{{- range $key, $value := .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $value.name | quote }}
  namespace: {{ $.Values.namespace | quote }}
  labels:
    app: {{ $value.appLabel | quote }}
spec:
  replicas: {{ $value.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $value.appLabel }}
  template:
    metadata:
      labels:
        app: {{ $value.appLabel }}
    spec:
      containers:
      - name: {{ $key }}-container
        image: {{ $value.image | quote }}
        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_USER
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PORT
        - name: DB_PASSWORD
          value: "{{ $.Values.database.password }}"
        command:
        - sh
        - -c
        - python manage.py migrate && python manage.py runserver 0.0.0.0:8000
        resources:
          requests:
            cpu: {{ $value.resources.requests.cpu | quote }}
            memory: {{ $value.resources.requests.memory | quote }}
          limits:
            cpu: {{ $value.resources.limits.cpu | quote }}
            memory: {{ $value.resources.limits.memory | quote }}
{{- end }}
