apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.deployments.api.serviceName }}
            port:
              number: 80
      - path: /public
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.deployments.public.serviceName }}
            port:
              number: 80
      - path: /static
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.deployments.public.serviceName }}
            port:
              number: 80
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tlsSecret }}
