{{- if .Values.serviceaccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "django-chart.serviceAccountName" . }}
  labels:
    {{- include "django-chart.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceaccount.automount }}
{{- end }}
