apiVersion: v1
kind: Service
metadata:
  name: public-service
  namespace: u-cptz2
spec:
  selector:
    app: public
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000  # Port sur lequel public écoute dans le conteneur
  type: ClusterIP
