apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: u-cptz2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: xinjie19/kubeapi:v5
        env:
        - name: DB_NAME
          value: "todolist"           # Nom de la base de données
        - name: DB_USER
          value: "xinjie"             # Nom d'utilisateur de la base de données
        - name: DB_PASSWORD
          value: "xinjie"             # Mot de passe de l'utilisateur
        - name: DB_HOST
          value: "dbservice"          # Nom du service de la base de données
        - name: DB_PORT
          value: "5432"               # Port de la base de données
        command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
