apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: u-cptz2  
spec:
  selector:
    app: my-app  
  ports:
    - protocol: TCP
      port: 80        # Port sur lequel le service va écouter
      targetPort: 5000  # Le port où ton application écoute dans le pod 
  type: ClusterIP  
